# Generated by Django 3.2.19 on 2023-07-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_image_like_post_rating_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_status',
            field=models.CharField(choices=[('Published', 'Published'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], default='Published', max_length=9),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('M', 'Moderator')], default='U', max_length=1),
        ),
    ]
