# Generated by Django 3.2.19 on 2023-07-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230716_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='post_status',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Published', 'Published'), ('Pending', 'Pending')], default='Published', max_length=9),
        ),
    ]
