# Generated by Django 3.2.19 on 2023-07-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_blog_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Published', 'Published')], default='Pending', max_length=9),
        ),
    ]
