# Generated by Django 3.2.19 on 2023-07-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_blog_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Admin'), ('M', 'Moderator')], default='U', max_length=1),
        ),
    ]
