# Generated by Django 3.2.19 on 2023-07-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230718_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Published', 'Published')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('M', 'Moderator'), ('A', 'Admin'), ('U', 'User')], default='U', max_length=1),
        ),
    ]
