# Generated by Django 3.2.19 on 2023-07-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_userprofile_profile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Published', 'Published'), ('Pending', 'Pending')], default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('U', 'User'), ('A', 'Admin'), ('M', 'Moderator')], default='U', max_length=1),
        ),
    ]
