# Generated by Django 3.2.19 on 2023-07-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230718_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('A', 'Admin'), ('U', 'User'), ('M', 'Moderator')], default='U', max_length=1),
        ),
    ]
